logdir: runs/reinforce/cartpole  # TensorBoard

env: CartPole-v0
# env: LunarLander-v2
render: False
hidden_sizes:
  - 64
  - 64
lr: 0.0003
activation: nn.ReLU
gamma: 0.99
epoch_steps: 2000
epochs: 2000
